fix(eslint-plugin-formatjs): remove obsolete @types/eslint (#5884)
eslint@9 comes with its own types. @types/eslint is unmaintained, no
longer compatible with current eslint, and causes spurious type errors
when installed.

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70735

---

Minimal reproduction:

**`eslint.config.mjs`**

```js
// @ts-check
import { FlatCompat } from "@eslint/eslintrc";
import { defineConfig } from "eslint/config";
const compat = new FlatCompat({ baseDirectory: "." });
export default defineConfig(compat.config({}));
```

```console
$ pnpm i @eslint/eslintrc eslint eslint-plugin-formatjs typescript
$ pnpm exec tsc --allowJs --module nodenext --noEmit eslint.config.mjs 
eslint.config.mjs:5:29 - error TS2345: Argument of type 'Config<RulesRecord>[]' is not assignable to parameter of type 'InfiniteArray<ConfigWithExtends>'.
  Type 'Config<RulesRecord>[]' is not assignable to type 'InfiniteArray<ConfigWithExtends>[]'.
    Type 'Config<RulesRecord>' is not assignable to type 'InfiniteArray<ConfigWithExtends>'.
      Type 'Config<RulesRecord>' is not assignable to type 'ConfigWithExtends'.
        Types of property 'languageOptions' are incompatible.
          Type 'import("/tmp/u/node_modules/.pnpm/@types+eslint@9.6.1/node_modules/@types/eslint/index").Linter.LanguageOptions' is not assignable to type 'import("/tmp/u/node_modules/.pnpm/@eslint+core@0.17.0/node_modules/@eslint/core/dist/cjs/types").LanguageOptions'.
            Index signature for type 'string' is missing in type 'LanguageOptions'.

5 export default defineConfig(compat.config({}));
                              ~~~~~~~~~~~~~~~~~


Found 1 error in eslint.config.mjs:5
```

Signed-off-by: Anders Kaseorg <andersk@mit.edu>